#!/usr/bin/env python3
"""
Diagnostic script to verify Q3 integration settings.
This helps identify secret mismatches between local and hosted environments.
"""

import os
import json
import time
import requests
from dotenv import load_dotenv

load_dotenv()

# All possible secrets from your .env
SECRETS_TO_TRY = {
    "Q3_INTEGRATION_SECRET": os.environ.get("Q3_INTEGRATION_SECRET", ""),
    "AIO_API_TOKEN": os.environ.get("AIO_API_TOKEN", ""),
    "AIO_CLIENT_SECRET": os.environ.get("AIO_CLIENT_SECRET", ""),
    "JWT_SECRET_KEY": os.environ.get("JWT_SECRET_KEY", ""),
}

ROLEVO_BASE_URL = "https://roleplays.trajectorie.com"
TEST_CLUSTER_ID = "6650b144-3dc"

print("=" * 60)
print("Q3 INTEGRATION DIAGNOSTICS")
print("=" * 60)

print("\n1. Secrets found in local .env:")
for name, value in SECRETS_TO_TRY.items():
    if value:
        print(f"   {name}: {value[:8]}...{value[-4:]}")
    else:
        print(f"   {name}: (not set)")

print("\n2. Testing cluster endpoint (no auth required):")
try:
    resp = requests.get(f"{ROLEVO_BASE_URL}/api/clusters", timeout=10)
    print(f"   Status: {resp.status_code}")
    if resp.ok:
        data = resp.json()
        if isinstance(data, list):
            print(f"   Found {len(data)} clusters")
            for c in data[:3]:
                cid = c.get('cluster_id') or c.get('id')
                name = c.get('name', 'Unknown')
                print(f"      - {cid}: {name}")
except Exception as e:
    print(f"   Error: {e}")

print("\n3. Testing JWT with each secret:")
import jwt
from datetime import datetime, timedelta

for secret_name, secret_value in SECRETS_TO_TRY.items():
    if not secret_value:
        continue
    
    print(f"\n   Testing with {secret_name}:")
    
    now = datetime.utcnow()
    payload = {
        "user_id": f"DIAG-{int(time.time())}",
        "assessment_cluster_id": TEST_CLUSTER_ID,
        "iat": int(now.timestamp()),
        "exp": int((now + timedelta(minutes=15)).timestamp()),
    }
    
    auth_token = jwt.encode(payload, secret_value, algorithm="HS256")
    
    launch_payload = {
        "user_id": payload["user_id"],
        "user_name": "Diagnostic Test",
        "assessment_cluster_id": TEST_CLUSTER_ID,
        "auth_token": auth_token,
        "return_url": "https://q3.example.com/dashboard",
        "results_url": "https://webhook.site/e1d69bf2-6cb7-4856-83a1-e394dce6cc33",
    }
    
    try:
        resp = requests.post(
            f"{ROLEVO_BASE_URL}/api/integration/assessment-launch",
            json=launch_payload,
            headers={"Content-Type": "application/json"},
            timeout=30,
        )
        
        if resp.status_code == 200:
            data = resp.json()
            if data.get("success"):
                print(f"   SUCCESS! This secret works on the hosted server.")
                print(f"   Redirect URL: {data.get('redirect_url')}")
            else:
                print(f"   Failed: {data.get('detail')}")
        elif resp.status_code == 401:
            print(f"   401 - JWT rejected (secret mismatch)")
        else:
            print(f"   {resp.status_code}: {resp.text[:100]}")
            
    except Exception as e:
        print(f"   Error: {e}")

print("\n" + "=" * 60)
print("NEXT STEPS")
print("=" * 60)
print("""
If all secrets show 401:
1. Check PythonAnywhere environment variables
2. Ensure Q3_INTEGRATION_SECRET matches on both ends
3. The hosted server uses: Q3_INTEGRATION_SECRET || AIO_CLIENT_SECRET || AIO_API_TOKEN

Your original URL token (UJz43kaHnwSAaqMkotVZqU2SvKWxCxsUxD0sebRgrzA) was:
- One-time token generated by assessment-launch (not a JWT)
- Already consumed or expired (tokens are valid for ~10 minutes)

To get a FRESH token:
1. Call POST /api/integration/assessment-launch with valid JWT
2. Use the redirect_url from the response
""")
